# Generated by Django 3.2.8 on 2022-05-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_account_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='user', verbose_name='Avatar'),
        ),
    ]
