# Generated by Django 3.2.8 on 2022-05-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_account_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
