# Generated by Django 3.2.8 on 2022-05-23 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withrawable_balance', models.IntegerField(default=0)),
                ('account_balance', models.IntegerField(default=0)),
                ('ammount_to_withdraw', models.IntegerField(default=0)),
                ('widrawal_procedure', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, None)], default=4, null=True)),
                ('withdrawable_settime', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_phone_number', models.CharField(max_length=255, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets_tbl',
            },
        ),
    ]
