# Generated by Django 3.2.8 on 2022-06-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_withdrawals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawals',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
